loggers:
  root:
    level: DEBUG
server:
  port: 8081
application:
  title: ALUCAR-APP
  version: 1.0.0.0-SNAPSHOT
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:banco-alucar
    username: adimn
    password: a.123456
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect